#!/bin/bash

# keyboard settings
# setxkbmap -layout us,cz -option grp:alt_space_toggle
setxkbmap -layout us,cz -option grp:alt_shift_toggle &

# run custom script to adjust displays according the situation
~/bin/display-adjust &

# enable sound
start-pulseaudio-x11 &
