#!/bin/bash

# keyboard settings
# setxkbmap -layout us,cz -option grp:alt_space_toggle
setxkbmap -layout us,cz -option grp:alt_shift_toggle &

# run custom script to adjust displays according the situation
~/bin/display-adjust &

# enable sound
start-pulseaudio-x11 &

# start ssh agent
if [ -z $SSH_AGENT_PID ] && [ -z $SSH_TTY ]; then  # if no agent & not in ssh
    eval `ssh-agent -s` > /dev/null
fi
